### ISSUE TITLE
Specify which actors to which columns

### ISSUE THREAD

**Issue by jamesmontalvo3** [xOPERATIONS/pat#16]
Make a way to map actors to columns. Typically you'd have:

```
Column   | Actor(s)
IV/SSRMS | Everyone but EV1 & EV2
EV1      | EV1
EV2      | EV2
```

But perhaps we have an EVA where most of the work is on EV1, and it makes sense to compress EV2 and IV/SSRMS columns. In that case perhaps generalize the name of that column, like "Others".

```
Column   | Actor(s)
EV1      | EV1
Others   | Everyone else, including EV2
```

Or perhaps EV1 is heavily working with the robotic arm (SSRMS), so those get compressed together:

```
Column    | Actor(s)
Others    | Everyone but EV1, EV2, SSRMS
EV1/SSRMS | EV1, SSRMS
EV2       | EV2
```

If a column has more than one actor, you need to prefix each step:

```
1. EV1: Do stuff
2. SSRMS: Do robotic stuff
3. EV1: Do more human stuff
```

But perhaps you define a certain actor as the primary on the column. So if EV1 was the primary in the above example, you'd instead get:

```
1. Do stuff
2. SSRMS: Do robotic stuff
3. Do more human stuff
```

At present, a procedure has actors defined like:

```yaml
actors:
  - role: IV/SSRMS
  - role: EV1
    name: Drew
  - role: EV2
    name: Taz
```

Instead perhaps this should be defined like:

```yaml
columns:
  - name: IV/SSRMS
    actors: "*"
  - name: EV1 (Drew)
    actors: EV1
  - name: EV2 (Taz)
    actors: EV2
```

**Comment by jamesmontalvo3** [comment]
Columns are specified like this now:

```yaml
columns:

  - key: IV
    actors: "*"
    display: IV/SSRMS

  - key: EV1
    actors: EV1
    display: EV1 (Drew)

  - key: EV3
    actors: EV3
    display: EV3 (Taz)
```
