### ISSUE TITLE
Bug: error thrown when actor only present in joint steps

### ISSUE THREAD

**Issue by jamesmontalvo3** [xOPERATIONS/pat#66]
If a task has many joint steps (e.g. `crewA + crewB`) but any members of a joint step do not have any solo steps of their own, then they will never be setup by `Task.getColumns()` and an error will be thrown:

```yaml
steps:

  - IV + crewA + crewB:
    - step: Step 1 for IV + crewA + crewB
    - step: Step 2 for IV + crewA + crewB

  - IV + crewA: This is a test of IV + crewA
  - crewA + crewB: This is a test of crewA + crewB

  - simo:
      IV: Do some IV stuff
      crewA + crewB:
        - title: SETUP
          duration:
            minutes: 10
        - step: "{{CHECK}} Work together"
        - step: to get the job done!
```

Example error:

```
$ pat build
PAT v3.0.0-rc1

Generating procedure from EVA1.yml
Creating EVA format
C:\path\to\pat\app\model\Task.js:129
                        throw new Error(`Unknown actor "${actorKey}" passed to getColumnIndex.
                        ^

Error: Unknown actor "EV1" passed to getColumnIndex.
                                Column index = {"IV":0}
    at Task.getColumnIndex (C:\path\to\pat\app\model\Task.js:129:10)
    at jointActorColumnKeys.map (C:\path\to\pat\app\writer\task\EvaDivisionWriter.js:37:27)
    at Array.map (<anonymous>)
    at getJointActorColumnInfo (C:\path\to\pat\app\writer\task\EvaDivisionWriter.js:36:60)
    at EvaDivisionWriter.prepareDivision (C:\path\to\pat\app\writer\task\EvaDivisionWriter.js:107:17)
    at EvaDocxTaskWriter.writeDivision (C:\path\to\pat\app\writer\task\EvaDocxTaskWriter.js:51:29)
    at EvaDocxTaskWriter.writeDivisions (C:\path\to\pat\app\writer\task\TaskWriter.js:131:13)
    at EvaDocxProcedureWriter.renderTask (C:\path\to\pat\app\writer\procedure\EvaDocxProcedureWriter.js:96:15)
    at EvaDocxProcedureWriter.renderTasks (C:\path\to\pat\app\writer\procedure\ProcedureWriter.js:158:9)
    at C:\path\to\pat\pat.js:66:11
```

The probable solution here is to modify  `Task.getColumns()` to handle `actor1 + actor2` scenarios.
