### ISSUE TITLE
actor and columnKeys not set on sub-steps

### ISSUE THREAD

**Issue by jamesmontalvo3** [xOPERATIONS/pat#68]
Substeps like these do not get `actor` or `columnKeys` set. Is that okay or a bug?

```yaml
      IV:
        - step: 'Do a bigger step:'
          substeps:
            - step: some substep.
            - step: another substep'
```
